version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - docker build -t fitness-app .
      - docker tag fitness-app:latest <account_id>.dkr.ecr.<region>.amazonaws.com/fitness-app:latest
  post_build:
    commands:
      - aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <account_id>.dkr.ecr.<region>.amazonaws.com
      - docker push <account_id>.dkr.ecr.<region>.amazonaws.com/fitness-app:latest
